### ISSUE TITLE
net_watcher项目：基于eBPF的无侵入式网络分析工具开发建设

### ISSUE THREAD

**Issue by helight** [linuxkerneltravel/lmp#542]
net_watcher 项目：目标是分析主机中指定进程或者服务网络情况。比如当处于流量高峰时间段时，服务可能会进入高负载状态。另外还有服务的一些并发量，调用延时，应用层和网络层的分析。本课题要求能够在一般主机环境下都可以进行应用层协议和网络层分析，应用层协议分析主要目标是分析http协议（1.1，2，3）；网络层协议主要分析tcp/ip层。本题目要求在LMP现有子项目(https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Network_Subsystem/net_watcher)，并将借鉴https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/sidecar 中的部分实现，基础之上继续迭代，优化现有网络性能监测功能，增加更多的网络可观测功能和指标。
实现目标：
●主机环境下对tcp/ip协议的分析，可以统计流量，延时，错误，链接信息等主要信息
●主机环境下对用户态http1的分析，可以分析出流量，延时，错误等信息
●主机环境下对用户态http2，3的分析
●主机环境下对用户态redis的分析
●主机环境下对用户态mysql的分析
●项目完整可运行，在github上有自动化测试流程，有单元测试和集成测试
项目技术要求
● 熟悉Linux内核网络系统的技术原理
● 熟悉Linux eBPF技术，能够通过eBPF实现内核事件的解析
运行要求：
● 运行系统： ubuntu22.4 以上
●场景验证：能在主机场景下完成课题实现目标，并有测试分析报告。

### TODO
- [ ] 代码追加注释和测试说明
- [x] 修复代码中现有已知问题
- #648 修改不能取到发包的问题
- #685 netfilter 在网络层延迟时间
- [x] 主机环境下对udp的分析，可以分析出流量，延时等信息
- #604 抽象传输层 获取UDP处理时间
- #610 增加参数控制udp输出
- #661 udp收包流量分析添加到netwatcher、实现数据在终端和log文件同步输出
- #664 udp send
- [x] 对采集数据进行可视化展示，使用prometheus，grafana进行展示
- #678 Prometheus监控网络数据包的相关指标，通过Grafana进行可视化展示
- [x] netfilter收发延时
- #737
- [x] icmp协议收发延时
- #742
- [ ] 主机环境下对用户态http1的分析，可以分析出流量，延时，错误等信息
- [ ] 主机环境下对用户态http2，3的分析
- [ ] HTTP 接收/发送请求量和耗时
- [x] Redis 查询请求量和耗时
- #835
- #839
- #852
- [x] MySQL 查询请求量和耗时
- #822 
- #831
- #851
- [ ] TCP 连接建立数量和耗时
- [ ] TCP RTT 统计
- [ ] TCP 实时连接数、TIME_WAIT、CLOSE_WAIT
- [x] DNS 请求/响应及数量（新版）
- #807
- #831
- [x]  TCP 丢包及数量
- #732
- #808
- #817
- [x] TCP 状态切换
- #752

**Comment by zhangxianyu777** [comment]
张铭轩本周工作
1、学习libbpf基础概念和相关流程
2、跑libbpf-bootstrap中sample的相关示例代码三个，对其中不了解的知识内容加以了解
3、netwatcher中对相关源码（300行左右）进行注释
下周工作
1、对相关知识进行加深理解
2、将剩下的sample示例代码看完
3、将netwatcher的源码看完

**Comment by wynyibo** [comment]
王月妮本周工作：
（1）tcp_win工具运行起来并完成了注释
（2）通过了解编写一个简单ebpf程序，简单了解挂载方法，可以用ebpf实现打印task_struct信息
下周计划：
（1）继续学习ebpf，学习网络基础知识
