### ISSUE TITLE
mem_watcher 项目：目标是分析主机中指定进程或者服务内存使用情况

### ISSUE THREAD

**Issue by helight** [linuxkerneltravel/lmp#545]
mem_watcher 项目：目标是分析主机中指定进程或者服务内存使用情况。比如当处于流量高峰时间段时，服务可能会进入高负载状态。本课题要求能够在一般主机环境下都可以进行内核系统和进程的内存分析，内存的分配回收，缺页、越界，泄露等等。本题目要求在LMP现有子项目(https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Memory_Subsystem)，基础之上继续迭代，并合并LMP下现有内存监测功能。
实现目标：
●主机环境下对系统内存进行分析，可以统计内存的分配回收，缺页等相关指标。
●主机环境下对指定进程进行分析，如申请和命中预分配，内存越界和内存泄露检测。
●对采集数据进行可视化展示，使用prometheus，grafana进行展示
●项目完整可运行，在github上有自动化测试流程，有单元测试和集成测试
项目技术要求
● 熟悉Linux内核内存系统的技术原理
● 熟悉Linux eBPF技术，能够通过eBPF实现内核事件的解析
运行要求：
● 运行系统： ubuntu22.4 以上
●场景验证：能在主机场景下完成课题实现目标，并有测试分析报告。
●文档丰富：具有Readme，设计文档等。

### Done
- [x] mem_watcher 项目创建
  #576 建立mem_watcher项目
- [x] [memleak](https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Memory_Subsystem/memleak) 所有内存相关能力整合到 mem_watcher 项目
- [x] [memstat](https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Memory_Subsystem/memstat) 所有内存相关能力整合到 mem_watcher 项目

### TODO
- [x] [paf](https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Memory_Subsystem/paf)所有内存相关能力整合到 mem_watcher 项目
- [x] [pr](https://github.com/linuxkerneltravel/lmp/tree/develop/eBPF_Supermarket/Memory_Subsystem/pr)所有内存相关能力整合到 mem_watcher 项目
- [x] 增加 Readme 文件，对 mem_watcher 的代码结构，功能能力、用法和使用场景进行详细说明。
- [x] 规范 mem_watcher 中相关文件的文件名。
- [x] 清理已经合并到 mem_watcher 后，不用的代码：memleak，memstat，paf，pr 等代码文件夹进行清理
- [x] 计算UMA内存碎片化程度功能
- [x] 添加计算NUMA架构下，所有内存节点的相关信息获取
- [x] 计算在NUMA架构下内存碎片化程度 
- [x] 监控SLAB 分配器的内存使用情况
- [ ] 跟踪共享内存的用量信息

**Comment by Super-Lzzx** [comment]
完成上周师兄布置的作业，安装lmp/eBPF_Supermarket/Memory_Subsystem，运行现有工具procstat（进程内存状态报告），sysstat（系统内存状态报告），paf，pr。

**Comment by syxl-time** [comment]
安装了lmp/eBPF_Supermarket/Memory_Subsystem，运行现有工具procstat（进程内存状态报告），sysstat（系统内存状态报告），paf，pr。

**Comment by yunkeying** [comment]
完成了交换页延迟指标的监测，成功采集数据

**Comment by yunkeying** [comment]
增加Makefile文件，按照要求把代码整理在mem_watch目录下，提交pr

**Comment by helight** [comment]
<img width="420" alt="image" src="https://github.com/linuxkerneltravel/lmp/assets/433500/2e6bf70c-282d-41e1-b0f5-603db0f5cc81">
